layout_spectrum: 0.9366001
name: Chica
typography_spectrum: 0.3299752
color:
  brandStrength: 0.8751798
  saturation: 0.7503399
  lightness: 0.4636806
  rhythmicContrast: 0.1439684
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
