layout_spectrum: 0.9366001
name: Chica
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8751798
  lightness: 0.1670839
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#E3BFB3'
    - '#CF545E'
    - '#736E87'
    - '#B6838C'
    - '#F7D5D9'
typography_spectrum: 0.2609512
